// ---------------------------------------------------------------------------
// Mac Brew Farm: Authentic data & menu items.
// ---------------------------------------------------------------------------

export const site = {
  name: 'Mac Brew Farm',
  city: 'Bengaluru',
  tagline: 'Good food. Great pours. Even better vibes.',
  subtagline: 'Open-air dining, craft pours, and live beats under green canopies in Bengaluru.',
  mapsUrl: 'https://maps.app.goo.gl/RtQ9ZF1NsLNxJRQh9?g_st=ic',
  address: 'Bengaluru, Karnataka, India',
  hours: 'Daily, 12:00 PM – 1:00 AM',
  phone: '+91 98450 12345',
  whatsapp: '919845012345',
  instagram: 'https://instagram.com/macbrewfarm',
  email: 'hello@macbrewfarm.com',
};

// ---------------------------------------------------------------------------
// Signature Cocktails & Craft Pours with Authentic Real-World Photos
// ---------------------------------------------------------------------------
export const cocktails = [
  {
    id: 'pom-rita',
    name: 'Pom Rita',
    category: 'signature',
    categoryLabel: 'Signature Craft',
    price: 595,
    tagline: 'Bold, ruby crimson with an agave citrus kick',
    desc: 'Tequila, Triple Sec, Agave Syrup, Fresh Lime Juice, Pomegranate Juice',
    notes: ['Crisp Tartness', 'Smoked Agave', 'Ruby Crimson'],
    profile: { strength: 70, sweetness: 50, citrus: 85, aroma: 65 },
    color: '#D6284F',
    foam: 0.35,
    garnish: '#F2A72B',
    img: 'media/img/pomrita.webp',
    isHero: true,
  },
  {
    id: 'herbal-rose',
    name: 'The Herbal Rose',
    category: 'botanical',
    categoryLabel: 'Botanical & Floral',
    price: 595,
    tagline: 'Botanical gin misted with distilled rose & sweet vermouth',
    desc: 'Gin, Campari, Sweet Vermouth, Wild Rose Syrup, Torched Rosemary, Silky Espuma',
    notes: ['Aromatic Floral', 'Herbal Bitters', 'Velvet Foam'],
    profile: { strength: 65, sweetness: 55, citrus: 40, aroma: 95 },
    color: '#C73C7C',
    foam: 0.7,
    garnish: '#E8A0C0',
    img: 'media/img/herbal-rose.webp',
    isHero: true,
  },
  {
    id: 'system-hack',
    name: 'System Hack & Fresh Pints',
    category: 'brews',
    categoryLabel: 'In-House Brews',
    price: 695,
    tagline: 'Our signature high-voltage cocktail blended with in-house craft beer',
    desc: 'Vodka, Gin, Tequila, White Rum, Triple Sec, Fresh Lime, In-House Golden Craft Beer',
    notes: ['Hoppy Citrus', 'High Proof', 'Golden Amber'],
    profile: { strength: 90, sweetness: 35, citrus: 60, aroma: 75 },
    color: '#C8701E',
    foam: 0.85,
    garnish: '#9CC34A',
    img: 'media/img/beer-pints.webp',
    isHero: true,
  },
  {
    id: 'oreo-lady',
    name: 'Oreo Lady',
    category: 'indulgence',
    categoryLabel: 'Decadent & Sweet',
    price: 495,
    tagline: 'Espresso martini elevated with dark cacao and Oreo crema',
    desc: 'Vodka, Kahlua, Single Origin Espresso, Madagascar Vanilla Syrup, Stamped Oreo Ice Cream',
    notes: ['Dark Roast Coffee', 'Creamy Chocolate', 'Dessert Cocktail'],
    profile: { strength: 60, sweetness: 85, citrus: 10, aroma: 80 },
    color: '#4A2A1A',
    foam: 0.6,
    garnish: '#2C1D18',
    img: 'media/img/oreo-lady.webp',
    isHero: true,
  },
  {
    id: 'honey-mango-katli',
    name: 'Honey Mango Katli',
    category: 'tropical',
    categoryLabel: 'Tropical & Fusion',
    price: 595,
    tagline: 'Alphonso nectar infused with cashew katli and wild forest honey',
    desc: 'Vodka (Kaju Katli Infusion), Fresh Alphonso Mango Pulp, Whipped Curd, Himalayan Pink Salt, Forest Honey',
    notes: ['Rich Mango Nectar', 'Nutty Sweetness', 'Silky Curd'],
    profile: { strength: 55, sweetness: 80, citrus: 45, aroma: 85 },
    color: '#F4B53F',
    foam: 0.2,
    garnish: '#F6B93B',
    img: 'media/img/mango-drink.webp',
    isHero: true,
  },
  {
    id: 'mac-brew-splash',
    name: 'Mac Brew Splash',
    category: 'tropical',
    categoryLabel: 'Tropical & Light',
    price: 595,
    tagline: 'Crisp tequila lifted by fragrant lychee and sparkling white wine',
    desc: 'Silver Tequila, Key Lime Juice, Hand-Pressed Lychee Nectar, Crisp White Wine Float',
    notes: ['Fragrant Lychee', 'Sparkling Wine', 'Zesty Lime'],
    profile: { strength: 60, sweetness: 65, citrus: 70, aroma: 85 },
    color: '#E6E2AE',
    foam: 0.1,
    garnish: '#F3EFE0',
    img: 'media/img/lychee-cocktail.webp',
  },
  {
    id: 'coconut-cloud',
    name: 'Coconut Cloud',
    category: 'tropical',
    categoryLabel: 'Tropical & Creamy',
    price: 545,
    tagline: 'Slow-pressed coconut milk with dark rum and roasted coconut rim',
    desc: 'Spiced Rum, Coconut Cream, Roasted Coconut Shavings, Pineapple Reduction, Nutmeg Dust',
    notes: ['Toasted Coconut', 'Velvety Cream', 'Warm Spice'],
    profile: { strength: 60, sweetness: 75, citrus: 30, aroma: 85 },
    color: '#D4C5B0',
    foam: 0.5,
    garnish: '#EADBC8',
    img: 'media/img/coconut-cocktail.webp',
  },
  {
    id: 'pineapple-punch',
    name: 'Pineapple Solstice',
    category: 'tropical',
    categoryLabel: 'Tropical & Zesty',
    price: 545,
    tagline: 'Charred golden pineapple shaken with spiced cane rum and tiki bitters',
    desc: 'Dark Aged Rum, Fresh Charred Pineapple Nectar, Maraschino Cherry, Angostura Bitters',
    notes: ['Charred Caramel', 'Tropical Fruit', 'Aged Oak'],
    profile: { strength: 65, sweetness: 70, citrus: 65, aroma: 75 },
    color: '#E59B2A',
    foam: 0.3,
    garnish: '#E8861D',
    img: 'media/img/pineapple-cocktail.webp',
  },
  {
    id: 'flight-trio',
    name: 'The Farm Tasting Trio',
    category: 'signature',
    categoryLabel: 'Tasting Flight',
    price: 1195,
    tagline: 'Experience three contrasting pours side by side',
    desc: 'Flight of three miniature signature cocktails: Cocoa-dusted Crema, Pomegranate Ruby, and Golden Tropical Citrus',
    notes: ['Full Spectrum Tasting', 'Ideal for Sharing', 'Artisan Presentation'],
    profile: { strength: 80, sweetness: 65, citrus: 70, aroma: 90 },
    color: '#A03045',
    foam: 0.5,
    garnish: '#F5D061',
    img: 'media/img/three-cocktails.webp',
  },
  {
    id: 'smokin-pumpkin',
    name: 'Smokin Pumpkin',
    category: 'signature',
    categoryLabel: 'Signature Craft',
    price: 595,
    tagline: 'Smoky bourbon paired with house-spiced pumpkin puree',
    desc: 'Smoked Whiskey, Fresh Lime Juice, Homemade Spiced Pumpkin Puree, Maple Mist',
    notes: ['Smoked Oak', 'Warm Autumn Spice', 'Silky Body'],
    profile: { strength: 75, sweetness: 50, citrus: 40, aroma: 80 },
    color: '#D9822B',
    foam: 0.15,
    garnish: '#E8861D',
    img: 'media/img/pomrita-poster.webp',
  },
  {
    id: 'basil-spritz',
    name: 'Basil Spritz',
    category: 'botanical',
    categoryLabel: 'Botanical & Floral',
    price: 495,
    tagline: 'Effervescent garden spritz crowned with vibrant green basil foam',
    desc: 'Botanical Gin, Artisan Tonic, Basil Espuma Foam, Crushed Pink Peppercorns',
    notes: ['Fresh Garden Herb', 'Crisp Carbonation', 'Light & Refreshing'],
    profile: { strength: 50, sweetness: 35, citrus: 75, aroma: 90 },
    color: '#8DB580',
    foam: 0.8,
    garnish: '#5C9A3C',
    img: 'media/img/lychee-cocktail.webp',
  },
];

// ---------------------------------------------------------------------------
// Video Theater Reels with Real Footage
// ---------------------------------------------------------------------------
export const reels = [
  {
    id: 'golden-hour',
    title: 'Golden Hour in the Garden',
    subtitle: 'Where evening light filters through lush canopies and reflecting pools',
    video: 'media/video/reel-golden-hour.mp4',
    poster: 'media/video/reel-golden-hour.webp',
    duration: '0:14',
    badge: 'Atmosphere',
  },
  {
    id: 'ambience',
    title: 'Fountains, Lights & Vibrance',
    subtitle: 'Stepped water cascades, woven lanterns, and the buzz of Bengaluru nights',
    video: 'media/video/reel-ambience.mp4',
    poster: 'media/video/reel-ambience.webp',
    duration: '0:12',
    badge: 'Architecture',
  },
  {
    id: 'feast',
    title: 'The Grand Table Feast',
    subtitle: 'Started with a drink, ended with an unforgettable communal spread',
    video: 'media/video/feast-table.mp4',
    poster: 'media/video/feast-table.webp',
    duration: '0:10',
    badge: 'Feast & Table',
  },
  {
    id: 'kitchen-craft',
    title: 'Wok Fire & Culinary Craft',
    subtitle: 'Fresh ingredients, sizzling grills, and handcrafted delicacies from our open kitchen',
    video: 'media/video/reel-good-food.mp4',
    poster: 'media/video/reel-good-food.webp',
    duration: '0:11',
    badge: 'Kitchen Art',
  },
];

// ---------------------------------------------------------------------------
// Spaces & Architecture of Mac Brew Farm
// ---------------------------------------------------------------------------
export const spaces = [
  {
    id: 'curved-pavilion',
    name: 'The Curved Pavilion & Pond',
    tag: 'Architectural Feature',
    desc: 'Sweeping organic curves hugging the reflecting water pond, blurring indoor and outdoor dining.',
    img: 'media/img/space-building.webp',
  },
  {
    id: 'island-bar',
    name: 'The Emerald Island Bar',
    tag: 'Craft Centerpiece',
    desc: 'Leaf-sculpted pillars and warm backlit amber shelves where expert mixologists craft signature pours.',
    img: 'media/img/space-bar.webp',
  },
  {
    id: 'woven-lamps',
    name: 'Handcrafted Cane Pendants',
    tag: 'Warm Lighting',
    desc: 'Dramatic custom woven lanterns casting intimate golden honeycombs across dining tables.',
    img: 'media/img/space-lamps.webp',
  },
  {
    id: 'stepped-fountain',
    name: 'Stepped Cascade & Fountain',
    tag: 'Water Feature',
    desc: 'The soothing murmur of stepped fountains creating a serene oasis away from the city bustle.',
    img: 'media/img/space-fountain.webp',
  },
  {
    id: 'night-canopy',
    name: 'Lantern Seating After Dark',
    tag: 'Evening Vibes',
    desc: 'Atmospheric garden seating illuminated by amber lanterns under the starry Bengaluru night sky.',
    img: 'media/img/space-night.webp',
  },
  {
    id: 'garden-lounge',
    name: 'Lush Garden Lounge',
    tag: 'Relaxed Seating',
    desc: 'Comfortable booth seating nestled among tropical foliage and towering architectural palms.',
    img: 'media/img/space-lounge.webp',
  },
];

// ---------------------------------------------------------------------------
// Kitchen Highlights with Authentic Photos
// ---------------------------------------------------------------------------
export const kitchenDishes = [
  {
    id: 'khao-soi',
    name: 'Burmese Khausuey',
    type: 'asian',
    diet: 'veg-nonveg',
    desc: 'Aromatic coconut yellow curry with flat noodles, charred shallots, chili oil, and crispy noodle nest.',
    img: 'media/img/khao-soi.webp',
    badge: 'Chef Signature',
  },
  {
    id: 'chicken-skewers',
    name: 'Char-Grilled Skewers',
    type: 'grill',
    diet: 'non-veg',
    desc: 'Tender chicken skewers marinated in garden herbs and spices, served with fresh citrus radish salad.',
    img: 'media/img/chicken-skewers.webp',
    badge: 'Popular',
  },
  {
    id: 'green-herb-chicken',
    name: 'Green Herb Masala Chicken',
    type: 'mains',
    diet: 'non-veg',
    desc: 'Crispy rice noodle nest over tender spiced chicken with microgreens and emerald mint emulsion.',
    img: 'media/img/green-chicken-a.webp',
    badge: 'House Specialty',
  },
  {
    id: 'garlic-butter-shrimp',
    name: 'Pan-Seared Garlic Shrimp',
    type: 'starters',
    diet: 'non-veg',
    desc: 'Plump coastal shrimp bathed in a rich garlic butter broth with toasted crusty sourdough bread.',
    img: 'media/img/shrimp.webp',
    badge: 'Seafood',
  },
  {
    id: 'wok-noodles',
    name: 'Wok-Tossed Street Noodles',
    type: 'asian',
    diet: 'veg',
    desc: 'Hand-pulled noodles stir-fried with scallions, sesame oil, wok-charred vegetables, and fiery sambal.',
    img: 'media/img/noodles.webp',
    badge: 'Wok Fire',
  },
  {
    id: 'gadbad-sundae',
    name: 'Royal Gadbad Ice Cream',
    type: 'dessert',
    diet: 'veg',
    desc: 'Three generous scoops of artisan ice cream layered with tropical fruits, nuts, jelly, and chocolate soil.',
    img: 'media/img/gadbad.webp',
    badge: 'Classic Dessert',
  },
  {
    id: 'artisan-dessert',
    name: 'Chocolate Forest & Toffee Leaf',
    type: 'dessert',
    diet: 'veg',
    desc: 'Velvety dark chocolate gateau, cherries, crunchy caramel leaf, and bean vanilla bean quenelle.',
    img: 'media/img/dessert-plate.webp',
    badge: 'Patisserie',
  },
];

// ---------------------------------------------------------------------------
// Digital Menu for Search and Full Browsing
// ---------------------------------------------------------------------------
const saladPrices = [295, 355, 475];
const salad = (name, desc, diet = 'veg') => ({ name, desc, prices: saladPrices, diet });

export const menu = [
  {
    id: 'cocktails',
    label: 'Cocktails & Brews',
    title: 'Signature Cocktails & Fresh Pours',
    theme: { band: '#3B1A1D', ink: '#6E3441', badge: '#3B1A1D' },
    items: cocktails.map((c) => ({
      name: c.name,
      desc: c.desc + '.',
      price: c.price,
      img: c.img,
      diet: 'veg',
      tag: c.categoryLabel,
    })),
  },
  {
    id: 'salads',
    label: 'Global Salads',
    title: 'Salads from Around the World',
    theme: { band: '#1B3A2D', ink: '#2F5A47', badge: '#1B3A2D' },
    columns: ['Veg', 'Chicken', 'Prawns'],
    items: [
      salad('Melon Aguachili', 'Avocado, Tomato, Palm Hearts, Queso Fresco & Tomato Water Chilled Broth'),
      salad('Grape Ceviche', 'Green Grapes, Cilantro, Shallots, Pepper & Orange Reduction'),
      salad('Mexican Salad Bowl', 'Layered Guacamole, Sour Cream, Refried Beans, Crisp Tortilla, Tomato Salsa'),
      salad('Crispy Potato Chips Salad', 'Crispy Potato Slivers, Scallion, Tomato, Onions, Pickles and Molasses'),
      salad('Classic Som Tam', 'Vegetarian Thai Raw Mango Salad with Crushed Peanuts and Bird Eye Chili'),
      salad('Buddha Fruit Salad', 'Petit Seasonal Fruits, Roasted Walnuts, Greek Labneh and Honey Drizzle'),
      salad('Tahini Miso Green', 'Wok-Stewed Tossed Miso Greens: Pak Choi, Broccoli, Scallion and Water Chestnuts'),
      salad('Tropical Fruit Caesar', 'Grilled Vegetables, Crisp Iceberg, Romaine Lettuce, Garlic Herb Crostini Croutons'),
    ],
  },
  {
    id: 'mains',
    label: 'Kitchen Mains',
    title: 'Main Course & Global Kitchen',
    theme: { band: '#2F4A33', ink: '#4A5B3A', badge: '#2F4A33' },
    groups: [
      {
        label: 'Burmese & Asian Bowls',
        items: [
          { name: 'Burmese Khausuey', desc: 'Slow-cooked spiced coconut broth, egg noodles, customizable crunchy condiments (Veg / Chicken / Prawns)', price: 495, img: 'media/img/khao-soi.webp', diet: 'non-veg' },
          { name: 'Hakka Street Noodles', desc: 'Wok tossed scallions, bell peppers, soy reduction', price: 345, img: 'media/img/noodles.webp', diet: 'veg' },
          { name: 'Thai Basil Fried Rice', desc: 'Fragrant jasmine rice with holy basil and red chili', price: 345, diet: 'veg' },
        ],
      },
      {
        label: 'Grills & Small Plates',
        items: [
          { name: 'Charred Chicken Skewers', desc: 'Served with pickled radish and sumac garlic labneh', price: 445, img: 'media/img/chicken-skewers.webp', diet: 'non-veg' },
          { name: 'Green Herb Masala Chicken', desc: 'Tender chicken in cilantro herb sauce with crispy noodle nest', price: 475, img: 'media/img/green-chicken-a.webp', diet: 'non-veg' },
          { name: 'Garlic Butter Sautéed Shrimp', desc: 'Served with toasted sourdough baguette', price: 545, img: 'media/img/shrimp.webp', diet: 'non-veg' },
        ],
      },
      {
        label: 'Artisan Pastas',
        items: [
          { name: 'Arrabbiata Di Pomodoro', desc: 'San Marzano tomatoes, garlic, extra virgin olive oil, chili flakes', price: 425, diet: 'veg' },
          { name: 'Creamy Alfredo Rustica', desc: 'Parmigiano-Reggiano, sweet cream, cracked black pepper', price: 445, diet: 'veg' },
          { name: 'Aglio Olio e Peperoncino', desc: 'Toasted garlic slivers, parsley, chili flakes, aged parmesan', price: 425, diet: 'veg' },
        ],
      },
      {
        label: 'Curries, Biryanis & Tandoor',
        items: [
          { name: 'Chicken Dum Biryani', desc: 'Slow-steamed aged basmati with saffron, mint, and tender bone-in chicken', price: 495, diet: 'non-veg' },
          { name: 'Mutton Awadhi Biryani', desc: 'Fragrant Awadhi spiced rice with succulent lamb chunks', price: 595, diet: 'non-veg' },
          { name: 'Paneer Makhni', desc: 'Slow-simmered rich tomato and cashew gravy with fresh cottage cheese', price: 395, diet: 'veg' },
          { name: 'Dal Pappu MBF Style', desc: 'Tempered lentils with roasted garlic, curry leaves, and cumin', price: 295, diet: 'veg' },
        ],
      },
    ],
  },
  {
    id: 'desserts',
    label: 'Artisan Desserts',
    title: 'Sweet Finales & Confections',
    theme: { band: '#C49A6C', ink: '#A97F55', badge: '#86654A' },
    items: [
      { name: 'Royal Gadbad Sundae', desc: 'Three scoops of premium ice cream, layered fruits, nuts, chocolate soil', price: 395, img: 'media/img/gadbad.webp', diet: 'veg' },
      { name: 'Pistachio Burnt Cheese Cake', desc: 'Classic caramelized Basque cheesecake with Sicilian pistachio cream', price: 395, diet: 'veg' },
      { name: 'Chocolate Forest & Ice Cream', desc: 'Dark chocolate gateau, cherry compote, chocolate crumb, vanilla ice cream', price: 395, img: 'media/img/dessert-plate.webp', diet: 'veg' },
      { name: 'Salted Caramel Gooey Brownie', desc: 'Sizzling hot brownie, vanilla bean ice cream, hot sea salt caramel drizzle', price: 395, diet: 'veg' },
      { name: 'Charred Coconut Creme Brulee', desc: 'Slow cooked burnt coconut cream with brittle sugar crust', price: 395, diet: 'veg' },
      { name: 'White Chocolate Lava Bomb', desc: 'Warm white chocolate core bursting over frozen cream', price: 395, diet: 'veg' },
      { name: 'Banana Halwa Parcel & Malai', desc: 'Crispy filo parcels filled with Malenadu banana halwa and saffron rabri', price: 395, diet: 'veg' },
    ],
  },
];
